using System;
using System.Collections.Generic;
using UnityEngine;
using BlackboardSystem;
using ServiceLocator;

public class BlackboardController: MonoBehaviour
{
    [SerializeField] BlackboardData blackboardData;
    readonly Blackboard blackboard = new Blackboard();
    readonly Arbiter arbiter = new Arbiter();

    private void Awake()
    {
        Locator.Subscribe(this);

        blackboardData.SetValuesOnBlackboard(blackboard);
        blackboard.Debug();
    }

    public Blackboard GetBlackboard() => blackboard;

    public void RegisterExpert(IExpert expert) => arbiter.RegisterExpert(expert);

    //public void DeRegisterExpert(IExpert expert) => arbiter.DeRegisterExpert(expert);

    private void Update()
    {
        // Execute all agreed actions from the current iteration
        foreach(var action in arbiter.BlackboardIteration(blackboard))
        {
            action();
        }
    }
}
